#Full address
GET http://localhost:8080/update?addr=192.38.139.87&secret=nesdrnw4e5gwsr&domain=vaskovasilev.eu
Accept: application/json

###

#Subdomain
GET http://localhost:8080/update?secret=nesdrnw4e5gwsr&addr=1.1.1.1&domain=mamavesi
Accept: application/json

###

#Resolve from caller address
#GET http://localhost:8080/update?secret=nesdrnw4e5gwsr&domain=vaskovasilev.eu
GET http://31b1e4a9cb70.ngrok.io/update?secret=nesdrnw4e5gwsr&domain=vaskovasilev.eu
Accept: application/json

###
GET https://us-central1-demoproject-280919.cloudfunctions.net/goddns?secret=secret&addr=1.1.1.1&domain=mamavesi