steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - goddns
      - --source=.
      - --entry-point
      - GoDDns
      - --runtime
      - go113
      - --trigger-http
      - --allow-unauthenticated
      #- --set-env-vars=ZONE=myzone,DOMAIN=mycomain.com,TTL=300,PROVIDER=google,VERBOSE=true,API_KEY=mykey,GCP_PROJECT=google-project
    env: ['GOPATH=/gopath']
    dir: './'